name: flutter_swiper_tv_yana
description: The best swiper(carousel) for flutter, with multiple layouts, infinite loop. Compatible with Android & iOS.
version: 1.1.9-nullsafety
homepage: https://github.com/YannetGorob/flutter_swiper_tv_yana.git

dependencies:
  flutter:
    sdk: flutter

  transformer_page_view_tv: ^0.1.6-nullsafety
  flutter_page_indicator_tv: ^0.0.3-nullsafety

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=0.1.4 <3.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter